name: CI

permissions:
  contents: write

on:
  pull_request:
    branches: [main, staging, dev]
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install requirements
        run: |
          pip install -r requirements.txt

      - name: Run lint
        run: |
          python -m compileall .

      - name: Run tests (dummy example)
        run: |
          echo "✅ CI rodou com sucesso!"

  auto_pr_staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'

    steps:
      - name: Create Pull Request to staging
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "staging"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Auto PR from dev to staging"
          pr_body: "Merge automático da branch dev → staging"
